service: factory-inc
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          method: post
          path: /send
      - httpApi:
          method: get
          path: /status
